service: hello-serverless

provider:
  memorySize: 256
  name: aws
  region: us-west-2
  runtime: nodejs10.x
  stage: dev
  timeout: 10

functions:
  add:
    events:
      - http:
          cors: true
          method: post
          path: math/add
    handler: add.handler

  hello:
    handler: hello.handler
    memorySize: 128
    timeout: 3
    vpc:
      securityGroupIds:
        - sg-13e25058
      subnetIds:
        - subnet-1692ae6f
        - subnet-f491c8bf
        - subnet-081c1252
        - subnet-e95ed8c2